modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/UnlimitedPeripheralWorks/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="peripheralworks"
version="${file.jarVersion}"
displayName="UnlimitedPeripheralWorks"
displayURL="https://docs.siredvin.site/UnlimitedPeripheralWorks/"

credits=""
authors="SirEdvin"
description='''
Peripheral mod, that provides a lot extra features, new peripherals and even some items
'''

[[dependencies.peripheralworks]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"